-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  peer_nodes

CREATE TABLE IF NOT EXISTS peer_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  "type" TEXT NOT NULL,
  location VARCHAR(120) NULL,
  status TEXT NOT NULL DEFAULT 'active',
  last_seen TIMESTAMPTZ(6) NULL,
  meta JSONB NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_peer_type CHECK ("type" IN ('postgres','mysql','app','service')),
  CONSTRAINT chk_peer_status CHECK (status IN ('active','offline','degraded','disabled'))
);
